spring.application.name=salary-management

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/salary_management}
spring.datasource.username=${DB_USERNAME:salary_app}
spring.datasource.password=${DB_PASSWORD:salary_app}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=250
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.flyway.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info

app.seed.enabled=false
