CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(30) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    department VARCHAR(100) NOT NULL,
    job_title VARCHAR(120) NOT NULL,
    country VARCHAR(80) NOT NULL,
    currency CHAR(3) NOT NULL,
    employment_status VARCHAR(20) NOT NULL,
    hire_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE compensations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    base_salary NUMERIC(19, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    bonus NUMERIC(19, 2) NOT NULL DEFAULT 0,
    allowances NUMERIC(19, 2) NOT NULL DEFAULT 0,
    pay_frequency VARCHAR(20) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_employees_department ON employees(department);
CREATE INDEX idx_employees_country ON employees(country);
CREATE INDEX idx_employees_status ON employees(employment_status);
CREATE INDEX idx_compensations_employee_effective_from ON compensations(employee_id, effective_from);
